name: Maestro CI

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

jobs:
  run-maestro:
    runs-on: macos-13   # ⬅️ CHANGED (було macos-14)
    timeout-minutes: 60

    env:
      APK_PATH: app-under-test.apk
      TEST_FILE: aos_tests/AosCheckRootMsg.yaml
      REPORT_DIR: maestro-report

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Maestro CLI
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      # --- Download APK from Google Drive via secret GDRIVE_URL ---
      - name: Install gdown (for Google Drive)
        run: python -m pip install --upgrade pip gdown

      - name: Download APK from Google Drive
        env:
          GDRIVE_URL: ${{ secrets.GDRIVE_URL }}
          APK_PATH: ${{ env.APK_PATH }}
        run: |
          test -n "$GDRIVE_URL" || { echo "Secret GDRIVE_URL is missing"; exit 1; }
          gdown --fuzzy "$GDRIVE_URL" -O "$APK_PATH"
          test -s "$APK_PATH" || { echo "Downloaded APK is empty"; exit 1; }
          ls -lh "$APK_PATH"

      # ⬅️ CHANGED: підкачуємо x86_64 образ для API 33 (стабільний на macos-13)
      - name: Preinstall Android 33 system image (x86_64)
        run: |
          sdkmanager --install "platforms;android-33" \
            "system-images;android-33;google_apis;x86_64" \
            "emulator" "platform-tools"

      # ⬅️ CHANGED: x86_64 конфіг на macOS-13
      - name: Run Maestro on Android emulator (API 33)
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33                 # ⬅️ CHANGED (замість 34)
          arch: x86_64                  # ⬅️ CHANGED (було arm64-v8a)
          target: google_apis           # лишаємо google_apis
          profile: pixel_5              # стабільний профіль під x86_64
          avd-name: ci-api33-x86        # ⬅️ CHANGED (нове ім’я AVD)
          force-avd-creation: true
          emulator-boot-timeout: 900
          emulator-options: >-
            -wipe-data
            -no-snapshot-load -no-snapshot-save
            -no-window -no-boot-anim
            -gpu swiftshader_indirect
            -camera-back none -camera-front none
            -noaudio
          disable-animations: true
          script: |
           set -euxo pipefail

           # Діагностика HVF та ADB
           $ANDROID_HOME/emulator/emulator -accel-check || true
           adb devices

           # Перевіримо сумісність ABI: що всередині APK і що підтримує емуль
           echo "== APK native ABIs =="
           (unzip -l "$APK_PATH" 'lib/*/*.so' | awk '{print $4}' | cut -d/ -f2 | sort -u) || echo "no native libs"
           echo "== Device ABIs =="
           adb shell getprop ro.product.cpu.abilist || true

           # Трошки часу девайсу "прокинутись" перед інсталом
           adb wait-for-device
           adb shell getprop sys.boot_completed

           # Перевіримо вільне місце на /data (на всяк випадок)
           adb shell df -h /data || true
           # Стабільна інсталяція: без streaming. Якщо не вийшло — fallback через push + pm install
           set +e
           adb install --no-streaming -r "$APK_PATH"
           INSTALL_RC=$?
           if [ $INSTALL_RC -ne 0 ]; then
            echo "Streamed install failed (rc=$INSTALL_RC). Fallback to push + pm install..."
            adb push "$APK_PATH" /data/local/tmp/app.apk
            adb shell pm install -t -r /data/local/tmp/app.apk
            INSTALL_RC=$?
           fi
           set -e

           if [ $INSTALL_RC -ne 0 ]; then
            echo "::error::APK install failed. Ймовірна причина — ABI mismatch (наприклад, APK arm64-only, а емуль x86_64)."
            echo "Див. 'APK native ABIs' vs 'Device ABIs' вище."
           exit $INSTALL_RC
           fi

           mkdir -p "$REPORT_DIR"
           maestro test "$TEST_FILE" --format junit --output "$REPORT_DIR/results.xml"


      - name: Upload Maestro report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: maestro-report
          path: ${{ env.REPORT_DIR }}/results.xml
          if-no-files-found: warn

      - name: Upload Maestro session artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: maestro-session-artifacts
          path: .maestro/**/*
          if-no-files-found: warn

      # ⬅️ CHANGED: додаємо пошук логів для нового AVD і, про всяк, старого ARM
      - name: Debug dump on failure
        if: failure()
        run: |
          $ANDROID_HOME/emulator/emulator -accel-check || true
          $ANDROID_HOME/emulator/emulator -version || true
          adb version || true
          echo "== AVD dir ==" && ls -la ~/.android/avd || true
          tail -n +1 ~/.android/avd/ci-api33-x86.avd/*.log ~/.android/avd/ci-api34-arm.avd/*.log 2>/dev/null || true
          echo "== ADB status ==" && adb devices || true
          adb shell getprop sys.boot_completed || true
          adb shell getprop init.svc.bootanim || true
          df -h ~ || true
